# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- demo

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet tool install --global dotnet-ef --configfile nuget.config --ignore-failed-sources
    dotnet-ef --version
  displayName: "Install EF Tools"

- task: NuGetAuthenticate@0
  inputs:
    forceReinstallCredentialProvider: true

- task: NuGetToolInstaller@1
  displayName: "Install NuGet"

- task: NuGetCommand@2
  displayName: "Restore NuGet packages"
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config
    nugetConfigPath: 'nuget.config'

- task: VSBuild@1
  displayName: "Build the solution"
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: |
    dotnet-ef migrations script --project .\IUGOCare.Infrastructure\ --context ApplicationDbContext --startup-project .\IUGOCare.API\ --idempotent --output $(Build.ArtifactStagingDirectory)/iugocare_migrations.sql
  displayName: "Generate EF Migration"

- script: |
    dotnet-ef migrations script --project .\IUGOCare.Audit\ --context AuditDbContext --startup-project .\IUGOCare.API\ --idempotent --output $(Build.ArtifactStagingDirectory)/iugocare_audit_migrations.sql
  displayName: "Generate EF Audit Migration"

- task: DotNetCoreCLI@2
  displayName: "Run Tests"
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: 'call yarn run test:unit:once'
  workingDirectory: '.\IUGOCare.API\PatientPortal\'
  displayName: "Run Vue Jest Unit Tests"

- powershell: |
    & SqlLocalDb info
    & SqlLocalDb create MSSQLLocalDB -s
    & SqlLocalDb info MSSQLLocalDB
    & sqlcmd -S "(LocalDb)\MSSQLLocalDB" -Q "CREATE DATABASE IUGOCare;"
  displayName: "Create DB"

- powershell: |
    & dotnet ef database update --project .\IUGOCare.Infrastructure\ --context ApplicationDbContext --startup-project .\IUGOCare.API\
    & dotnet ef database update --project .\IUGOCare.Audit\ --context AuditDbContext --startup-project .\IUGOCare.API\
  displayName: "Run migrations"

- task: DotNetCoreCLI@2
  displayName: "Publish"
  env:
    NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS: 60
    NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS: 60
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-r linux-x64 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    modifyOutputPath: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.\IUGOCare.API\PatientPortal\dist'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/DemoWeb.zip'

- task: PublishBuildArtifacts@1
  displayName: "Upload Artifacts"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'WebApi'
