//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IUGOCare.Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IUGOCare.Application.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is required..
        /// </summary>
        internal static string CurrentPasswordRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is wrong..
        /// </summary>
        internal static string CurrentPasswordWrong {
            get {
                return ResourceManager.GetString("CurrentPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is required..
        /// </summary>
        internal static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the email address is incorrect..
        /// </summary>
        internal static string EmailAddressWrongFormat {
            get {
                return ResourceManager.GetString("EmailAddressWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a confirmation that your email address on your iUGO Care Patient Portal account has been successfully changed on {{DateStamp}} at {{TimeStamp}}..
        /// </summary>
        internal static string EmailUpdatedBody_1 {
            get {
                return ResourceManager.GetString("EmailUpdatedBody_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you made these changes, no action is required. If you did not make these changes, contact your provider to report this..
        /// </summary>
        internal static string EmailUpdatedBody_2 {
            get {
                return ResourceManager.GetString("EmailUpdatedBody_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,&lt;br /&gt;The iUGO Care Team.
        /// </summary>
        internal static string EmailUpdatedBody_3 {
            get {
                return ResourceManager.GetString("EmailUpdatedBody_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address has been successfully updated!.
        /// </summary>
        internal static string EmailUpdatedSubject {
            get {
                return ResourceManager.GetString("EmailUpdatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address has been updated on the iUGO Care platform..
        /// </summary>
        internal static string EmailUpdateRequestBody_1 {
            get {
                return ResourceManager.GetString("EmailUpdateRequestBody_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the link below to verify your new email address:.
        /// </summary>
        internal static string EmailUpdateRequestBody_2 {
            get {
                return ResourceManager.GetString("EmailUpdateRequestBody_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a style=&quot;text-decoration: underline;&quot;  href=&quot;{{Url}}&quot; target=&quot;_blank&quot;&gt;{{Url}}&lt;/a&gt;.
        /// </summary>
        internal static string EmailUpdateRequestBody_3 {
            get {
                return ResourceManager.GetString("EmailUpdateRequestBody_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not make these changes, disregard this email and contact your provider to report this..
        /// </summary>
        internal static string EmailUpdateRequestBody_4 {
            get {
                return ResourceManager.GetString("EmailUpdateRequestBody_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,&lt;br /&gt;The iUGO Care Team.
        /// </summary>
        internal static string EmailUpdateRequestBody_5 {
            get {
                return ResourceManager.GetString("EmailUpdateRequestBody_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email address.
        /// </summary>
        internal static string EmailUpdateRequestSubject {
            get {
                return ResourceManager.GetString("EmailUpdateRequestSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {{PatientName}},.
        /// </summary>
        internal static string GenericEmailGreeting {
            get {
                return ResourceManager.GetString("GenericEmailGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect..
        /// </summary>
        internal static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address provided is already in use..
        /// </summary>
        internal static string NewEmailInUse {
            get {
                return ResourceManager.GetString("NewEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password is required..
        /// </summary>
        internal static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a confirmation that your password has been successfully changed on {{DateStamp}} at {{TimeStamp}}..
        /// </summary>
        internal static string PasswordChangedBody_1 {
            get {
                return ResourceManager.GetString("PasswordChangedBody_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you made these changes, no action is required. If you did not make these changes, contact your provider to report this..
        /// </summary>
        internal static string PasswordChangedBody_2 {
            get {
                return ResourceManager.GetString("PasswordChangedBody_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,&lt;br /&gt;The iUGO Care Team.
        /// </summary>
        internal static string PasswordChangedBody_3 {
            get {
                return ResourceManager.GetString("PasswordChangedBody_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully updated!.
        /// </summary>
        internal static string PasswordChangedSubject {
            get {
                return ResourceManager.GetString("PasswordChangedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 8 characters in length.
        /// </summary>
        internal static string PasswordRequirement_1 {
            get {
                return ResourceManager.GetString("PasswordRequirement_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower case letters (a-z).
        /// </summary>
        internal static string PasswordRequirement_2 {
            get {
                return ResourceManager.GetString("PasswordRequirement_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper case letters (A-Z).
        /// </summary>
        internal static string PasswordRequirement_3 {
            get {
                return ResourceManager.GetString("PasswordRequirement_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (i.e. 0-9).
        /// </summary>
        internal static string PasswordRequirement_4 {
            get {
                return ResourceManager.GetString("PasswordRequirement_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too weak.
        /// </summary>
        internal static string PasswordStrengthError {
            get {
                return ResourceManager.GetString("PasswordStrengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient id is required..
        /// </summary>
        internal static string PatientIdRequired {
            get {
                return ResourceManager.GetString("PatientIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient must be active..
        /// </summary>
        internal static string PatientMustBeActive {
            get {
                return ResourceManager.GetString("PatientMustBeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your health care provider has enrolled you in iUGO Care..
        /// </summary>
        internal static string SendPatientOnboardingEmailBody_1 {
            get {
                return ResourceManager.GetString("SendPatientOnboardingEmailBody_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iUGO Care is a healthcare platform that allows you to receive high-quality healthcare anywhere. You’ll have access to a private and secure online portal for your doctor to track, monitor, and coordinate some of your healthcare needs or concerns..
        /// </summary>
        internal static string SendPatientOnboardingEmailBody_2 {
            get {
                return ResourceManager.GetString("SendPatientOnboardingEmailBody_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete your registration and access all of iUGO Care’s exciting features, please register your account online:.
        /// </summary>
        internal static string SendPatientOnboardingEmailBody_3 {
            get {
                return ResourceManager.GetString("SendPatientOnboardingEmailBody_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Step 1&lt;/b&gt; Click &lt;a style=&quot;text-decoration: underline;&quot;  href=&quot;{{Url}}&quot; target=&quot;_blank&quot;&gt;Register Now&lt;/a&gt;. A new webpage will be open in your internet browser..
        /// </summary>
        internal static string SendPatientOnboardingEmailBody_4 {
            get {
                return ResourceManager.GetString("SendPatientOnboardingEmailBody_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Step 2&lt;/b&gt; Follow the instructions to create a password for your account..
        /// </summary>
        internal static string SendPatientOnboardingEmailBody_5 {
            get {
                return ResourceManager.GetString("SendPatientOnboardingEmailBody_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Step 3&lt;/b&gt; Log into &lt;a style=&quot;text-decoration: underline;&quot; href=&quot;http://www.iugocare.com&quot; target=&quot;_blank&quot;&gt;www.iugocare.com&lt;/a&gt; using your password..
        /// </summary>
        internal static string SendPatientOnboardingEmailBody_6 {
            get {
                return ResourceManager.GetString("SendPatientOnboardingEmailBody_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe this email was sent to you in error, please disregard and delete it. If you have questions about how to use your iUGO Care portal, please contact your healthcare professional..
        /// </summary>
        internal static string SendPatientOnboardingEmailBody_7 {
            get {
                return ResourceManager.GetString("SendPatientOnboardingEmailBody_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Onboarding.
        /// </summary>
        internal static string SendPatientOnboardingEmailSubject {
            get {
                return ResourceManager.GetString("SendPatientOnboardingEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Onboarding.
        /// </summary>
        internal static string SendPatientOnboardingEmailButtonText {
            get {
                return ResourceManager.GetString("SendPatientOnboardingEmailButtonText", resourceCulture);
            }
        }
    }
}
